name: Release Excepcion_RCM

on:
  push:
    branches:
      - main
    paths:
      - 'Excepcion_RCM/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión del .jar (ej. 0.1)'
        required: true
        default: '0.1'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Excepcion_RCM

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Compile Java
        run: javac -encoding UTF-8 -source 8 -target 8 Excepcion_RCM.java

      - name: Create JAR with custom version
        run: jar cfm Excepcion_RCM_v${{ github.event.inputs.version }}.jar manifest.txt *.class

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Excepcion_RCM_v${{ github.event.inputs.version }}
          files: Excepcion_RCM/Excepcion_RCM_v${{ github.event.inputs.version }}.jar
