name: Release Orquesta_RCM

on:
  push:
    paths:
      - 'Orquesta_RCM/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Versión del .jar (ej. 0.1)'
        required: true
        default: '0.1'

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Orquesta_RCM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Java
        run: javac -encoding UTF-8 Orquesta_RCM.java

      - name: Create JAR with custom version
        run: jar cfm Orquesta_RCM_v${{ github.event.inputs.version }}.jar manifest.txt *.class

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Orquesta_RCM_v${{ github.event.inputs.version }}
          files: Orquesta_RCM/Orquesta_RCM_v${{ github.event.inputs.version }}.jar